#### 연평균 성장률 ( CAGR ) 구하기 

In [1]:
def getCAGR( first , last , years ):
    return (last/first)**(1/years)-1

In [12]:
cagr = getCAGR( 65300, 2669000, 20)
print("SEC  CAGR: {:.2%}".format(cagr))

SEC  CAGR: 20.38%


In [17]:
dic = {'name': 'richard choi', 'age': 50 }
print('%s %d' % (dic['name'], dic['age']))

richard choi 50


### Lamdba 

In [22]:
insertComma = lambda x : format(x,',')

In [23]:
insertComma( 2344546767)

'2,344,546,767'

In [24]:
help('modules')


Please wait a moment while I gather a list of all available modules...



C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\pkgutil.py:92: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(info.name)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\pkgutil.py:107: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  yield from walk_packages(path, info.name+'.', onerror)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")


IPython             cgitb               mmapfile            sspi
PIL                 charset_normalizer  mmsystem            sspicon
__future__          chunk               modulefinder        stack_data
_abc                cmath               mpl_finance         stat
_aix_support        cmd                 msilib              statistics
_argon2_cffi_bindings code                msvcrt              string
_ast                codecs              multiprocessing     stringprep
_asyncio            codeop              multitasking        struct
_bisect             collections         nbclient            subprocess
_blake2             colorama            nbconvert           sunau
_bootsubprocess     colorsys            nbformat            symtable
_bz2                commctrl            nest_asyncio        sys
_cffi_backend       compileall          netbios             sysconfig
_codecs             concurrent          netrc               tabnanny
_codecs_cn          configparser        nntp

In [25]:
help('modules time')


Here is a list of modules whose name or summary contains 'time'.
If there are any, enter a module name to get more help.

_datetime - Fast implementation of the datetime type.
time - This module provides various functions to manipulate time values.
_strptime - Strptime-related classes and functions.
asyncio.staggered - Support for running coroutines in parallel with staggered start times.
datetime - Concrete date/time and related types.
timeit - Tool for measuring execution time of small code snippets.
IPython.terminal.pt_inputhooks.tk - Wrapper around the eventloop that gives some time to the Tkinter GUI to process
IPython.utils.tz - Timezone utilities
cryptography.hazmat.primitives.constant_time 
dateutil.parser._parser - This module offers a generic date/time string parser which is able to parse
dateutil.tz.tz - This module offers timezone implementations subclassing the abstract
dateutil.tz.win - This module provides an interface to the native time zone data on Windows,
debugpy.co

pandas.tests.tools.test_to_datetime - test to_datetime
pandas.tests.tools.test_to_time 
pandas.tests.tools.test_to_timedelta 
pandas.tests.tseries.offsets.test_dst - Tests for DateOffset additions over Daylight Savings Time
pandas.tests.tslibs.test_array_to_datetime 
pandas.tests.tslibs.test_parsing - Tests for Timestamp parsing, aimed at pandas/_libs/tslibs/parsing.pyx
pandas.tests.tslibs.test_timedeltas 
pandas.tests.tslibs.test_timezones 
pandas.tseries.api - Timeseries API
pandas_datareader.av.time_series 
pandas_datareader.tests.av.test_av_time_series 
pymysql.times 
qtpy.QtMultimedia - Provides low-level multimedia functionality.
qtpy.QtMultimediaWidgets - Provides QtMultimediaWidgets classes and functions.
qtpy.tests.test_qtmultimedia 
qtpy.tests.test_qtmultimediawidgets - Test QtMultimediaWidgets.
scipy._lib.uarray - `uarray` provides functions for generating multimethods that dispatch to
scipy.fft._fftlog_multimethods 
scipy.signal._lti_conversion - ltisys -- a collection of f

In [26]:
help('datetime')

Help on module datetime:

NAME
    datetime - Fast implementation of the datetime type.

MODULE REFERENCE
    https://docs.python.org/3.10/library/datetime.html
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

CLASSES
    builtins.object
        date
            datetime
        time
        timedelta
        tzinfo
            timezone
    
    class date(builtins.object)
     |  date(year, month, day) --> date object
     |  
     |  Methods defined here:
     |  
     |  __add__(self, value, /)
     |      Return self+value.
     |  
     |  __eq__(self, value, /)
     |      Return self==value.
     |  
     |  __format__(...)
     |      Formats self with strftime.
     |  
     |  __ge__(self, value, /)
    

In [27]:
import keyword

In [28]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [29]:
keyword.__file__

'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\\lib\\keyword.py'

In [32]:
from calendar import month
print( month( 2022,9 ))

   September 2022
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30



In [33]:
import urllib.request
type( urllib.request)

module

In [34]:
urllib.__path__

['C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\\lib\\urllib']

In [35]:
urllib.__package__

'urllib'

### 객체지향 프로그래밍

#### 상속

In [42]:
class A:
    def methodA( self ):
        print('call A method A')
    def method( self ):
        print('call A method')

class B:
    def methodB( self ):
        print('call B method B')

class C(A,B):
    def methodC( self ):
        print('call C method C')
    def method( self):
        print('call Cs override method')
        super().method()

In [45]:
a_inst = C()
a_inst.method()

call Cs override method
call A method


#### Class method __init__ __del__ 

In [52]:
class NasdaqStock:
    """class for NasdaqStock"""
    count = 0
    def __init__(self, symbol, price):
        """Constructor for NasdaqStock""" 
        self.price = price
        self.symbol = symbol
        NasdaqStock.count += 1
        print('calling ___init__( {},{:.2f}) > count: {}'.format( self.symbol, self.price, NasdaqStock.count))
    def __del__(self):
        """Destructor for NasdaqStock"""
        print('calling __del__({})'.format(self))

In [53]:
gg = NasdaqStock('GOOG',1154.05)

calling ___init__( GOOG,1154.05) > count: 1


In [54]:
del(gg)

calling __del__(<__main__.NasdaqStock object at 0x000002264DF912A0>)


### numpy

In [55]:
import numpy as np 

a = np.random.randint( 2,12,(2,2))

In [56]:
a

array([[ 4, 11],
       [ 4, 10]])

In [58]:
c = a.T
c

array([[ 4,  4],
       [11, 10]])

In [60]:
c1 = a.flatten()
c1

array([ 4, 11,  4, 10])

In [68]:
a1 = a[0]
b1 = a[1]
c = np.vstack([a1, b1])
c

array([[ 4, 11],
       [ 4, 10]])

In [69]:
c2 = np.hstack( [a[0], a[1]])
c2

array([ 4, 11,  4, 10])

In [72]:
from pandas import Series 
s = Series(c2)
s

0     4
1    11
2     4
3    10
dtype: int32

In [73]:
s.iloc[-1]

10

In [74]:
s.values[:]

array([ 4, 11,  4, 10])

In [75]:
s.describe()

count     4.000000
mean      7.250000
std       3.774917
min       4.000000
25%       4.000000
50%       7.000000
75%      10.250000
max      11.000000
dtype: float64

In [79]:
import pandas as pd
df = pd.DataFrame()
df['count'] = s
df

count
0      4
1     11
2      4
3     10

In [81]:
df['종목명'] =['삼성전자','POSCO','케이티','LG전자']
df

count    종목명
0      4   삼성전자
1     11  POSCO
2      4    케이티
3     10   LG전자

In [83]:
df['주가'] =[56000,240000,60000,50000]
df

count    종목명      주가
0      4   삼성전자   56000
1     11  POSCO  240000
2      4    케이티   60000
3     10   LG전자   50000

In [84]:
df.columns

Index(['count', '종목명', '주가'], dtype='object')

In [87]:
s2 = Series( data =[ 3, '강원랜드', 38000], index = df.columns )
s2

count        3
종목명       강원랜드
주가       38000
dtype: object

In [89]:
df.loc[4] = s2
df

count    종목명      주가
0      4   삼성전자   56000
1     11  POSCO  240000
2      4    케이티   60000
3     10   LG전자   50000
4      3   강원랜드   38000

In [90]:
df.set_index('종목명')

count      주가
종목명                 
삼성전자       4   56000
POSCO     11  240000
케이티        4   60000
LG전자      10   50000
강원랜드       3   38000

In [92]:
for i in df.index:
    print(df.iloc[i])

count        4
종목명       삼성전자
주가       56000
Name: 0, dtype: object
count        11
종목명       POSCO
주가       240000
Name: 1, dtype: object
count        4
종목명        케이티
주가       60000
Name: 2, dtype: object
count       10
종목명       LG전자
주가       50000
Name: 3, dtype: object
count        3
종목명       강원랜드
주가       38000
Name: 4, dtype: object


In [94]:
for row in df.itertuples('종목명'):
    print(row)

Pandas(Index=0, count=4, 종목명='삼성전자', 주가=56000)
Pandas(Index=1, count=11, 종목명='POSCO', 주가=240000)
Pandas(Index=2, count=4, 종목명='케이티', 주가=60000)
Pandas(Index=3, count=10, 종목명='LG전자', 주가=50000)
Pandas(Index=4, count=3, 종목명='강원랜드', 주가=38000)


In [95]:
for row in df.iterrows():
    print(row)

(0, count        4
종목명       삼성전자
주가       56000
Name: 0, dtype: object)
(1, count        11
종목명       POSCO
주가       240000
Name: 1, dtype: object)
(2, count        4
종목명        케이티
주가       60000
Name: 2, dtype: object)
(3, count       10
종목명       LG전자
주가       50000
Name: 3, dtype: object)
(4, count        3
종목명       강원랜드
주가       38000
Name: 4, dtype: object)
